language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
    - /.*/
services:
  - docker

before_install:
  - docker pull eclipse-mosquitto
  - docker run -d -p 9001:9001 -v $(pwd)/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro eclipse-mosquitto
before_script:
  - npm install -g @angular/cli
  - npm install codecov -g
script:
  - ng lint
  - npm run test-headless
  - docker build .
scripts:

after_success:
  - codecov
