language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - npm install codecov -g
script:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href https://travis-ci.com/tobibechtold/smart-football-table-ui
scripts:

after_success:
  - codecov
