version: '2.0'

services:

  smart-football-table-ui:
    container_name: smart-football-table-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '80:80'

  eclipse-mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - default

  led-control:
    image: ledcontrol:0.0.1-SNAPSHOT
    environment:
      - device=/dev/ttyUSB4
      - LEDS=73
      - TTY=/dev/ttyUSB4
      - MQTTHOST=mqtt
      - MQTTPORT=1883
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"


