version: '3.5'

services:

  smart-football-table-ui:
    container_name: smart-football-table-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4200:4200'

  eclipse-mosquitto:
    image: eclipse-mosquitto
      hostname: mosquitto
      container_name: mosquitto
      expose:
        - "1883"
        - "9001"
      ports:
        - "1883:1883"
        - "9001:9001"
      volumes:
        - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      networks:
        - default
